import { ReactLenis } from "lenis/react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="flex min-h-full flex-col">
        <ReactLenis
          root
          options={{
            lerp: 0.14,
            duration: 0.8,
            smoothWheel: true,
            syncTouch: false,
          }}
        >
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
